# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/clean.smk"
include: "rules/prepare_reference.smk"
include: "rules/consensus.smk"
include: "rules/demux.smk"
include: "rules/align.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        ".demux_finished.flag",
        "consensus/bulk_consensus/consensus.fastq",
        "consensus/consensus_summary.csv",
        ".coverage.done",
        ".plot.done" #flag file,
    default_target: True
