# configuration of display in snakemake workflow catalog: https://snakemake.github.io/snakemake-workflow-catalog

usage:
  mandatory-flags:
    desc: "--use-conda can be used in place of --sdm conda. The pileline is not compatible with the --all-temp flag since this overrides protected()"
    flags: ["--sdm conda", "--cores", "--snakefile"]
    conda: true # whether pipeline works with '--sdm conda'
    apptainer: false # whether pipeline works with '--sdm apptainer/singularity'
    apptainer+conda: false # whether pipeline works with '--sdm conda apptainer/singularity'
    report: True # whether creation of reports using 'snakemake --report report.zip' is supported
