# \HEADER\-------------------------------------------------------------------------
#
#  CONTENTS      : Snakemake nanopore data pipeline
#
#  DESCRIPTION   : Alignment of the subreads onto the consensus generated by Medaka, pileup and plotting for QC reporting.
#
#  RESTRICTIONS  : none
#
#  REQUIRES      : none
#
# ---------------------------------------------------------------------------------


### Alignment to the consensus and coverage, consensus match calculation rules and plotting thereof
# -----------------------------------------------------
rule aln_to_consensus:
    conda: "../envs/align.yaml"
    input:
        consensus = lambda wildcards: [f for f in get_splits(wildcards, prefix="", suffix="_consensus.fastq") if wildcards.sample in f][0],
        reads = "demux/{sample}.fastq.gz"
    output:
        sam = "aln/{sample}_aln.sam",
        bam = "aln/{sample}_aln.bam",
        sorted_bam = "aln/{sample}_aln_sorted.bam",
        bai = "aln/{sample}_aln_sorted.bam.bai",
        cov = "report/{sample}_coverage.txt",
        pileup = "report/{sample}_mpileup.txt",
        coverage_flag = touch(".coverage_{sample}.done") 
    log:
        "logs/aln/{sample}_aln.log"
    shell:
        r"""
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting alignment" >> {log}
        minimap2 -ax map-ont {input.consensus} {input.reads} > {output.sam} 2>> {log}
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Alignment complete, converting to BAM" >> {log}
        
        samtools view -bo {output.bam} {output.sam} 2>> {log}
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] BAM conversion complete, sorting" >> {log}
        
        samtools sort {output.bam} -o {output.sorted_bam} 2>> {log}
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Sorting complete, indexing" >> {log}
        
        samtools index {output.sorted_bam} 2>> {log}
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Indexing complete, generating coverage" >> {log}
        
        samtools depth -a -o {output.cov} {output.sorted_bam} 2>> {log}
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Coverage complete, generating pileup" >> {log}
        
        samtools mpileup -a -f {input.consensus} {output.sorted_bam} > {output.pileup} 2>> {log}
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Alignment workflow complete" >> {log}
        """


rule parse_mpileup_ref_match:
    conda: "../envs/align.yaml"
    input:
        "report/{sample}_mpileup.txt"
    output:
        "report/{sample}_pypileup.tsv"
    log:
        "logs/aln/{sample}_parse_mpileup_ref_match.log"
    run:
        import pandas as pd
        from common import parse_mpileup
        df_pileup = parse_mpileup(input[0])
        df_pileup.to_csv(output[0], sep='\t', index=False)

rule plot_coverage:
    conda: "../envs/align.yaml"
    input:
        "report/{sample}_pypileup.tsv"
    output:
        report("report/{sample}_coverage.pdf", category = "{sample}"), 
        report("report/{sample}_mismatch_freq.pdf", category = "{sample}"),
        plot_flag = touch(".plot_{sample}.done"), #flag file
    log:
        logf = "logs/aln/{sample}_plot_coverage.log"
    script:
        "../scripts/plot_coverage.py"

rule coverage_done:
    conda: "../envs/align.yaml"
    input:
        lambda wildcards: expand(".coverage_{sample}.done", sample=get_passed_samples(wildcards))
    output:
        touch(".coverage.done")
    log:
        logf = "logs/aln/coverage_done.log"
    run:
        with open(output[0], "w") as f:
            f.write("Coverage calculation completed.\n")

rule plot_done:
    conda: "../envs/align.yaml"
    input:
        lambda wildcards: expand(".plot_{sample}.done", sample=get_passed_samples(wildcards))
    output:
        touch(".plot.done")
    log:
        logf = "logs/aln/plot_done.log"
    run:
        with open(output[0], "w") as f:
            f.write("Coverage plotting completed.\n")
